apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x1w5f7kc9-java-springboot
  janus-idp.io/tekton: x1w5f7kc9-java-springboot
  backstage.io/kubernetes-id: x1w5f7kc9-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: x1w5f7kc9-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
